version: "3.7"

services:
  auth-service:
    image: studtool/auth-service:v0.0.1
    depends_on:
      - auth-storage
    environment:
      - STUDTOOL_AUTH_SERVICE_PORT=${STUDTOOL_AUTH_SERVICE_PORT}
      - STUDTOOL_JWT_KEY=${STUDTOOL_JWT_KEY}
      - STUDTOOL_AUTH_SERVICE_REPOSITORIES_ENABLED=true
      - STUDTOOL_AUTH_STORAGE_HOST=auth-storage
      - STUDTOOL_AUTH_STORAGE_PORT=5432
      - STUDTOOL_AUTH_STORAGE_NAME=auth
      - STUDTOOL_AUTH_STORAGE_USER=${STUDTOOL_AUTH_STORAGE_USER}
      - STUDTOOL_AUTH_STORAGE_PASSWORD=${STUDTOOL_AUTH_STORAGE_PASSWORD}
    ports:
      - ${STUDTOOL_AUTH_SERVICE_PORT}:80

  auth-storage:
    image: postgres:11.2
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=${STUDTOOL_AUTH_STORAGE_USER}
      - POSTGRES_PASSWORD=${STUDTOOL_AUTH_STORAGE_PASSWORD}
    ports:
      - ${STUDTOOL_AUTH_STORAGE_PORT}:5432
