version: "3.7"

services:
  gateway:
    image: quay.io/datawire/ambassador:0.60.2
    depends_on:
      - auth-service
      - users-service
      - documents-service
    volumes:
      - ./gateway:/ambassador/ambassador-config
    environment:
      - AMBASSADOR_NO_KUBEWATCH=no_kubewatch
    ports:
      - ${STUDTOOL_GATEWAY_PORT}:8080

  auth-service:
    image: studtool/auth-service:v0.0.1
    depends_on:
      - auth-storage
      - users-queue
    environment:
      - STUDTOOL_AUTH_SERVICE_PORT=80
      - STUDTOOL_AUTH_SERVICE_SHOULD_LOG_ENV_VARS=true
      - STUDTOOL_JWT_KEY=${STUDTOOL_JWT_KEY}
      - STUDTOOL_AUTH_SERVICE_SHOULD_ENABLE_REPOSITORIES=true
      - STUDTOOL_AUTH_STORAGE_HOST=${STUDTOOL_AUTH_STORAGE_HOST}
      - STUDTOOL_AUTH_STORAGE_PORT=${STUDTOOL_AUTH_STORAGE_PORT}
      - STUDTOOL_AUTH_STORAGE_NAME=${STUDTOOL_AUTH_STORAGE_NAME}
      - STUDTOOL_AUTH_STORAGE_USER=${STUDTOOL_AUTH_STORAGE_USER}
      - STUDTOOL_AUTH_STORAGE_PASSWORD=${STUDTOOL_AUTH_STORAGE_PASSWORD}
      - STUDTOOL_AUTH_SERVICE_SHOULD_ENABLE_QUEUES=true
      - STUDTOOL_USERS_MQ_HOST=${STUDTOOL_USERS_MQ_HOST}
      - STUDTOOL_USERS_MQ_PORT=${STUDTOOL_USERS_MQ_PORT}
      - STUDTOOL_USERS_MQ_USER=${STUDTOOL_USERS_MQ_USER}
      - STUDTOOL_USERS_MQ_PASSWORD=${STUDTOOL_USERS_MQ_PASSWORD}
      - STUDTOOL_CREATED_USERS_QUEUE_NAME=new_users

  auth-storage:
    image: studtool/auth-storage:v0.0.1
    environment:
      - POSTGRES_DB=${STUDTOOL_AUTH_STORAGE_NAME}
      - POSTGRES_USER=${STUDTOOL_AUTH_STORAGE_USER}
      - POSTGRES_PASSWORD=${STUDTOOL_AUTH_STORAGE_PASSWORD}

  users-service:
    image: studtool/users-service:v0.0.1
    depends_on:
      - users-storage
      - users-queue
    environment:
      - STUDTOOL_USERS_SERVICE_PORT=80
      - STUDTOOL_USERS_SERVICE_SHOULD_LOG_ENV_VARS=true
      - STUDTOOL_USERS_SERVICE_REPOSITORIES_ENABLED=true
      - STUDTOOL_USERS_STORAGE_HOST=${STUDTOOL_USERS_STORAGE_HOST}
      - STUDTOOL_USERS_STORAGE_PORT=${STUDTOOL_USERS_STORAGE_PORT}
      - STUDTOOL_USERS_STORAGE_NAME=${STUDTOOL_USERS_STORAGE_NAME}
      - STUDTOOL_USERS_SERVICE_QUEUES_ENABLED=true
      - STUDTOOL_USERS_MQ_HOST=${STUDTOOL_USERS_MQ_HOST}
      - STUDTOOL_USERS_MQ_PORT=${STUDTOOL_USERS_MQ_PORT}
      - STUDTOOL_USERS_MQ_USER=${STUDTOOL_USERS_MQ_USER}
      - STUDTOOL_USERS_MQ_PASSWORD=${STUDTOOL_USERS_MQ_PASSWORD}
      - STUDTOOL_CREATED_USERS_QUEUE_NAME=new_users

  users-storage:
    image: mongo:4.0

  documents-service:
    image: studtool/documents-service:v0.0.1
    environment:
      - STUDTOOL_DOCUMENTS_SERVICE_PORT=80
      - STUDTOOL_DOCUMENTS_SERVICE_SHOULD_LOG_ENV_VARS=true
      - STUDTOOL_DOCUMENTS_INFO_STORAGE_HOST=${STUDTOOL_DOCUMENTS_INFO_STORAGE_HOST}
      - STUDTOOL_DOCUMENTS_INFO_STORAGE_PORT=${STUDTOOL_DOCUMENTS_INFO_STORAGE_PORT}
      - STUDTOOL_DOCUMENTS_INFO_STORAGE_NAME=${STUDTOOL_DOCUMENTS_INFO_STORAGE_NAME}
      - STUDTOOL_DOCUMENTS_INFO_STORAGE_USER=${STUDTOOL_DOCUMENTS_INFO_STORAGE_USER}
      - STUDTOOL_DOCUMENTS_INFO_STORAGE_PASSWORD=${STUDTOOL_DOCUMENTS_INFO_STORAGE_PASSWORD}

  documents-info-storage:
    image: studtool/documents-info-storage:v0.0.1
    environment:
      - POSTGRES_DB=${STUDTOOL_DOCUMENTS_INFO_STORAGE_NAME}
      - POSTGRES_USER=${STUDTOOL_DOCUMENTS_INFO_STORAGE_USER}
      - POSTGRES_PASSWORD=${STUDTOOL_DOCUMENTS_INFO_STORAGE_PASSWORD}

  users-queue:
    image: rabbitmq:3.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=${STUDTOOL_USERS_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${STUDTOOL_USERS_MQ_PASSWORD}
    ports:
      - ${STUDTOOL_USERS_QUEUE_PORT}:15672
