version: "3.7"

services:
  gateway:
    image: quay.io/datawire/ambassador:0.60.1
    depends_on:
      - auth-service-v0
      - emails-service-v0
    volumes:
      - ./gateway:/ambassador/ambassador-config
    environment:
      - AMBASSADOR_NO_KUBEWATCH=no_kubewatch
    ports:
      - ${STUDTOOL_GATEWAY_PORT}:8080

  graphics:
    image: grafana/grafana:6.2.0
    depends_on:
      - monitor
    environment:
      - GF_SERVER_DOMAIN=${STUDTOOL_DOMAIN}
      - GF_SERVER_ROOT_URL=${STUDTOOL_GRAPHICS_ROOT_URL}
      - GF_SECURITY_ADMIN_PASSWORD=${STUDTOOL_GRAPHICS_PASSWORD}
    ports:
      - "${STUDTOOL_GRAPHICS_PORT}:3000"

  monitor:
    image: prom/prometheus:v2.9.2
    depends_on:
      - auth-service-v0
      - users-service-v0
    volumes:
      - ./monitor:/etc/prometheus
    ports:
      - ${STUDTOOL_MONITOR_PORT}:9090

  auth-service-v0:
    image: studtool/auth-service:v0.0.1
    depends_on:
      - auth-storage-v0
      - message-queue-v0
    environment:
      - STUDTOOL_AUTH_SERVICE_PORT=80
      - STUDTOOL_AUTH_SERVICE_SHOULD_LOG_ENV_VARS=true
      - STUDTOOL_JWT_KEY=${STUDTOOL_JWT_KEY}
      - STUDTOOL_JWT_VALID_PERIOD=30m
      - STUDTOOL_AUTH_SERVICE_SHOULD_CHECK_ACCOUNT_VERIFIED_ON_SIGN_IN=false
      - STUDTOOL_AUTH_SERVICE_SHOULD_ENABLE_REPOSITORIES=true
      - STUDTOOL_AUTH_STORAGE_HOST=${STUDTOOL_AUTH_STORAGE_HOST}
      - STUDTOOL_AUTH_STORAGE_PORT=${STUDTOOL_AUTH_STORAGE_PORT}
      - STUDTOOL_AUTH_STORAGE_NAME=${STUDTOOL_AUTH_STORAGE_NAME}
      - STUDTOOL_AUTH_STORAGE_USER=${STUDTOOL_AUTH_STORAGE_USER}
      - STUDTOOL_AUTH_STORAGE_PASSWORD=${STUDTOOL_AUTH_STORAGE_PASSWORD}
      - STUDTOOL_AUTH_SERVICE_SHOULD_ENABLE_QUEUES=true
      - STUDTOOL_TOKENS_STORAGE_HOST=${STUDTOOL_TOKENS_STORAGE_HOST}
      - STUDTOOL_TOKENS_STORAGE_PORT=${STUDTOOL_TOKENS_STORAGE_PORT}
      - STUDTOOL_MQ_HOST=${STUDTOOL_MQ_HOST}
      - STUDTOOL_MQ_PORT=${STUDTOOL_MQ_PORT}
      - STUDTOOL_MQ_USER=${STUDTOOL_MQ_USER}
      - STUDTOOL_MQ_PASSWORD=${STUDTOOL_MQ_PASSWORD}

  auth-storage-v0:
    image: studtool/auth-storage:v0.0.1
    environment:
      - POSTGRES_DB=${STUDTOOL_AUTH_STORAGE_NAME}
      - POSTGRES_USER=${STUDTOOL_AUTH_STORAGE_USER}
      - POSTGRES_PASSWORD=${STUDTOOL_AUTH_STORAGE_PASSWORD}

  tokens-storage-v0:
    image: redis:5.0.4

  users-management-service-v0:
    image: studtool/users-management-service:v0.0.1
    depends_on:
      - message-queue-v0
    environment:
      - STUDTOOL_USERS_SERVICE_SHOULD_LOG_ENV_VARS=true
      - STUDTOOL_MQ_HOST=${STUDTOOL_MQ_HOST}
      - STUDTOOL_MQ_PORT=${STUDTOOL_MQ_PORT}
      - STUDTOOL_MQ_USER=${STUDTOOL_MQ_USER}
      - STUDTOOL_MQ_PASSWORD=${STUDTOOL_MQ_PASSWORD}

  emails-service-v0:
    image: studtool/emails-service:v0.0.1
    depends_on:
      - message-queue-v0
    volumes:
      - ./templates:/tmp/templates
    environment:
      - STUDTOOL_EMAILS_SERVICE_SHOULD_LOG_ENV_VARS=true
      - STUDTOOL_SMTP_SERVER_HOST=${STUDTOOL_SMTP_SERVER_HOST}
      - STUDTOOL_SMTP_SERVER_PORT=${STUDTOOL_SMTP_SERVER_PORT}
      - STUDTOOL_SMTP_SERVER_USER=${STUDTOOL_SMTP_SERVER_USER}
      - STUDTOOL_SMTP_SERVER_PASSWORD=${STUDTOOL_SMTP_SERVER_PASSWORD}
      - STUDTOOL_SMTP_SERVER_SSL=${STUDTOOL_SMTP_SERVER_SSL}
      - STUDTOOL_MQ_HOST=${STUDTOOL_MQ_HOST}
      - STUDTOOL_MQ_PORT=${STUDTOOL_MQ_PORT}
      - STUDTOOL_MQ_USER=${STUDTOOL_MQ_USER}
      - STUDTOOL_MQ_PASSWORD=${STUDTOOL_MQ_PASSWORD}
      - STUDTOOL_REGISTRATION_EMAIL_TEMPLATE_PATH=/tmp/templates/reg.txt

  users-service-v0:
    image: studtool/users-service:v0.0.1
    depends_on:
      - users-storage-v0
    environment:
      - STUDTOOL_USERS_SERVICE_SHOULD_LOG_ENV_VARS=true
      - STUDTOOL_USERS_SERVICE_PORT=80
      - STUDTOOL_USERS_SERVICE_REPOSITORIES_ENABLED=true
      - STUDTOOL_USERS_SERVICE_QUEUES_ENABLED=true
      - STUDTOOL_USERS_STORAGE_HOST=${STUDTOOL_USERS_STORAGE_HOST}
      - STUDTOOL_USERS_STORAGE_PORT=${STUDTOOL_USERS_STORAGE_PORT}
      - STUDTOOL_USERS_STORAGE_NAME=${STUDTOOL_USERS_STORAGE_NAME}
      - STUDTOOL_MQ_HOST=${STUDTOOL_MQ_HOST}
      - STUDTOOL_MQ_PORT=${STUDTOOL_MQ_PORT}
      - STUDTOOL_MQ_USER=${STUDTOOL_MQ_USER}
      - STUDTOOL_MQ_PASSWORD=${STUDTOOL_MQ_PASSWORD}

  users-storage-v0:
    image: mongo:4.1.11

  documents-service-v0:
    image: studtool/documents-service:v0.0.1
    depends_on:
      - documents-info-storage-v0
      - message-queue-v0
    environment:
      - STUDTOOL_DOCUMENTS_SERVICE_SHOULD_LOG_ENV_VARS=true
      - STUDTOOL_DOCUMENTS_SERVICE_PORT=80
      - STUDTOOL_DOCUMENTS_INFO_STORAGE_HOST=${STUDTOOL_DOCUMENTS_INFO_STORAGE_HOST}
      - STUDTOOL_DOCUMENTS_INFO_STORAGE_PORT=${STUDTOOL_DOCUMENTS_INFO_STORAGE_PORT}
      - STUDTOOL_DOCUMENTS_INFO_STORAGE_NAME=${STUDTOOL_DOCUMENTS_INFO_STORAGE_NAME}
      - STUDTOOL_DOCUMENTS_INFO_STORAGE_USER=${STUDTOOL_DOCUMENTS_INFO_STORAGE_USER}
      - STUDTOOL_DOCUMENTS_INFO_STORAGE_PASSWORD=${STUDTOOL_DOCUMENTS_INFO_STORAGE_PASSWORD}
      - STUDTOOL_MQ_HOST=${STUDTOOL_MQ_HOST}
      - STUDTOOL_MQ_PORT=${STUDTOOL_MQ_PORT}
      - STUDTOOL_MQ_USER=${STUDTOOL_MQ_USER}
      - STUDTOOL_MQ_PASSWORD=${STUDTOOL_MQ_PASSWORD}

  documents-info-storage-v0:
    image: studtool/documents-info-storage:v0.0.1
    environment:
      - MYSQL_USER=${STUDTOOL_DOCUMENTS_INFO_STORAGE_USER}
      - MYSQL_PASSWORD=${STUDTOOL_DOCUMENTS_INFO_STORAGE_PASSWORD}
      - MYSQL_DATABASE=${STUDTOOL_DOCUMENTS_INFO_STORAGE_NAME}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  documents-storage-v0-metrics-exporter:
    image: prom/mysqld-exporter:v0.11.0
    environment:
      - DATA_SOURCE_NAME=${STUDTOOL_DOCUMENTS_STORAGE_EXPORTER_CONNECTION_STRING}

  message-queue-v0:
    image: rabbitmq:3.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=${STUDTOOL_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${STUDTOOL_MQ_PASSWORD}
    ports:
      - ${STUDTOOL_MQ_INTERFACE_PORT}:15672
