version: "3.7"

services:
  auth-service:
    image: studtool/auth-service:v0.0.1
    environment:
      - STUDTOOL_AUTH_SERVICE_PORT=80
      - STUDTOOL_JWT_KEY=${STUDTOOL_JWT_KEY}
      - STUDTOOL_AUTH_SERVICE_REPOSITORIES_ENABLED=true
      - STUDTOOL_AUTH_STORAGE_HOST=${STUDTOOL_AUTH_STORAGE_HOST}
      - STUDTOOL_AUTH_STORAGE_PORT=${STUDTOOL_AUTH_STORAGE_PORT}
      - STUDTOOL_AUTH_STORAGE_NAME=${STUDTOOL_AUTH_STORAGE_NAME}
      - STUDTOOL_AUTH_STORAGE_USER=${STUDTOOL_AUTH_STORAGE_USER}
      - STUDTOOL_AUTH_STORAGE_PASSWORD=${STUDTOOL_AUTH_STORAGE_PASSWORD}
      - STUDTOOL_AUTH_SERVICE_QUEUES_ENABLED=true
      - STUDTOOL_USERS_MQ_HOST=${STUDTOOL_USERS_MQ_HOST}
      - STUDTOOL_USERS_MQ_PORT=${STUDTOOL_USERS_MQ_PORT}
      - STUDTOOL_USERS_MQ_USER=${STUDTOOL_USERS_MQ_USER}
      - STUDTOOL_USERS_MQ_PASSWORD=${STUDTOOL_USERS_MQ_PASSWORD}
      - STUDTOOL_CREATED_USERS_QUEUE_NAME=new_users
    ports:
      - ${STUDTOOL_AUTH_SERVICE_PORT}:80

  users-service:
    image: studtool/users-service:v0.0.1
    depends_on:
      - users-storage
    environment:
      - STUDTOOL_USERS_SERVICE_PORT=80
      - STUDTOOL_USERS_SERVICE_REPOSITORIES_ENABLED=true
      - STUDTOOL_USERS_STORAGE_HOST=${STUDTOOL_USERS_STORAGE_HOST}
      - STUDTOOL_USERS_STORAGE_PORT=${STUDTOOL_USERS_STORAGE_PORT}
      - STUDTOOL_USERS_STORAGE_NAME=${STUDTOOL_USERS_STORAGE_NAME}
      - STUDTOOL_USERS_SERVICE_QUEUES_ENABLED=true
      - STUDTOOL_USERS_MQ_HOST=${STUDTOOL_USERS_MQ_HOST}
      - STUDTOOL_USERS_MQ_PORT=${STUDTOOL_USERS_MQ_PORT}
      - STUDTOOL_USERS_MQ_USER=${STUDTOOL_USERS_MQ_USER}
      - STUDTOOL_USERS_MQ_PASSWORD=${STUDTOOL_USERS_MQ_PASSWORD}
      - STUDTOOL_CREATED_USERS_QUEUE_NAME=new_users
    ports:
      - ${STUDTOOL_USERS_SERVICE_PORT}:80

  users-storage:
    image: mongo:4.0

  users-queue:
    image: rabbitmq:3.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=${STUDTOOL_USERS_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${STUDTOOL_USERS_MQ_PASSWORD}
    ports:
      - ${STUDTOOL_USERS_QUEUE_PORT}:15672
