version: "3.7"

services:
  discovery:
    image: consul:1.4.3
    depends_on:
      - auth-service-v0.0.1
    ports:
      - ${STUDTOOL_CONSUL_PORT}:8500

  auth-service-v0.1:
    image: studtool/auth-service:v0.0.1
    depends_on:
      - auth-storage-v0.0.1
    environment:
      - STUDTOOL_AUTH_SERVICE_PORT=80
      - STUDTOOL_AUTH_STORAGE_HOST=auth-storage-v0.0.1
      - STUDTOOL_AUTH_STORAGE_PORT=5432
      - STUDTOOL_AUTH_STORAGE_NAME=auth
      - STUDTOOL_AUTH_STORAGE_USER=${STUDTOOL_AUTH_STORAGE_USER}
      - STUDTOOL_AUTH_STORAGE_PASSWORD=${STUDTOOL_AUTH_STORAGE_PASSWORD}
      - STUDTOOL_SERVICE_DISCOVERY_ADDRESS=discovery:8500
    ports:
      - ${STUDTOOL_AUTH_SERVICE_PORT}:80

  auth-storage-v0.0.1:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=${STUDTOOL_AUTH_STORAGE_USER}
      - POSTGRES_PASSWORD=${STUDTOOL_AUTH_STORAGE_PASSWORD}
