version: "3.7"

services:
  discovery-service:
    image: consul:1.4.3
    depends_on:
      - auth-service-v0.0.1
    ports:
      - ${STUDTOOL_CONSUL_PORT}:8500

  auth-service-v0.0.1:
    image: studtool/auth-service:v0.0.1
    depends_on:
      - auth-storage-v0.0.1
      - users-queue-v0.0.1
    environment:
      - STUDTOOL_AUTH_SERVICE_SHOULD_LOG_ENV_VARS=true
      - STUDTOOL_AUTH_SERVICE_PORT=80
      - STUDTOOL_AUTH_STORAGE_HOST=auth-storage-v0.0.1
      - STUDTOOL_AUTH_STORAGE_PORT=5432
      - STUDTOOL_AUTH_STORAGE_NAME=auth
      - STUDTOOL_AUTH_STORAGE_USER=${STUDTOOL_AUTH_STORAGE_USER}
      - STUDTOOL_AUTH_STORAGE_PASSWORD=${STUDTOOL_AUTH_STORAGE_PASSWORD}
      - STUDTOOL_AUTH_STORAGE_SHOULD_INIT=true
      - STUDTOOL_AUTH_STORAGE_CONNECTION_NUM_RETRIES=5
      - STUDTOOL_AUTH_STORAGE_CONNECTION_RETRY_INTERVAL=2s
      - STUDTOOL_USERS_MQ_HOST=users-queue-v0.0.1
      - STUDTOOL_USERS_MQ_PORT=5672
      - STUDTOOL_USERS_MQ_USER=${STUDTOOL_USERS_QUEUE_USER}
      - STUDTOOL_USERS_MQ_PASSWORD=${STUDTOOL_USERS_QUEUE_PASSWORD}
      - STUDTOOL_USERS_MQ_CONNECTION_NUM_RETRIES=5
      - STUDTOOL_USERS_MQ_CONNECTION_RETRY_INTERVAL=3s
      - STUDTOOL_CREATED_USERS_QUEUE_NAME=created
      - STUDTOOL_DELETED_USERS_QUEUE_NAME=deleted
      - STUDTOOL_DISCOVERY_SERVICE_ADDRESS=discovery-service:8500
      - STUDTOOL_AUTH_SERVICE_DISCOVERY_CLIENT_ENABLED=true
      - STUDTOOL_AUTH_SERVICE_HEALTH_CHECK_TIMEOUT=10s
    ports:
      - ${STUDTOOL_AUTH_SERVICE_PORT}:80

  auth-storage-v0.0.1:
    image: postgres:11.2
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=${STUDTOOL_AUTH_STORAGE_USER}
      - POSTGRES_PASSWORD=${STUDTOOL_AUTH_STORAGE_PASSWORD}

  users-queue-v0.0.1:
    image: rabbitmq:3.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=${STUDTOOL_USERS_QUEUE_USER}
      - RABBITMQ_DEFAULT_PASS=${STUDTOOL_USERS_QUEUE_PASSWORD}
