version: "3.7"

services:
  gateway:
    image: quay.io/datawire/ambassador:0.50.3
    depends_on:
      - profiles-v0.0.1
      - timetable-v0.0.1
    ports:
    - ${STUDTOOL_GATEWAY_PORT}:80
    volumes:
    - ./gateway:/ambassador/ambassador-config
    environment:
    - AMBASSADOR_NO_KUBEWATCH=no_kubewatch

  prometheus:
    image: studtool/prometheus:v0.0.1
    depends_on:
      - profiles-v0.0.1
      - timetable-v0.0.1
    ports:
      - ${STUDTOOL_PROMETHEUS_PORT}:9090

  profiles-v0.0.1:
    image: studtool/profiles:v0.0.1
    depends_on:
      - profiles-storage-v0.0.1
    environment:
      - STUDTOOL_PROFILES_STORAGE_HOST=profiles-storage-v0.0.1
      - STUDTOOL_PROFILES_STORAGE_PORT=27017
    ports:
      - ${STUDTOOL_PROFILES_PORT}:80

  profiles-storage-v0.0.1:
    image: mongo:4.0.6

  timetable-v0.0.1:
    image: studtool/timetable:v0.0.1
    depends_on:
      - timetable-storage-v0.0.1
    environment:
      - STUDTOOL_TIMETABLE_STORAGE_HOST=timetable-storage-v0.0.1
      - STUDTOOL_TIMETABLE_STORAGE_PORT=27017
    ports:
      - ${STUDTOOL_TIMETABLE_PORT}:80

  timetable-storage-v0.0.1:
    image: mongo:4.0.6
