version: "3.7"

services:
  prometheus:
    image: "studtool/prometheus:v0.0.1"
    depends_on:
      - profiles
    ports:
      - "${STUDTOOL_PROMETHEUS_PORT}:9090"

  profiles:
    image: "studtool/profiles:v0.0.1"
    depends_on:
      - profiles-storage
    environment:
      - STUDTOOL_PROFILES_STORAGE_HOST=profiles-storage
      - STUDTOOL_PROFILES_STORAGE_PORT=27017
    ports:
      - "${STUDTOOL_PROFILES_PORT}:80"

  profiles-storage:
    image: "mongo:4.0.6"

